"""Agrega tabla genero y relacion con libro

Revision ID: 0f5ab569096b
Revises: 95dd46a75b66
Create Date: 2026-10-09 16:09:25.615622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel #-> Coreccion manual, se agrego esta impotancion porque el autogenerate omitio, para evitar el NameError al crear la columna

# revision identifiers, used by Alembic.
revision: str = '0f5ab569096b'
down_revision: Union[str, None] = '95dd46a75b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.add_column('libro', sa.Column('genero_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_libro_genero_id'), 'libro', ['genero_id'], unique=False)
    op.create_foreign_key(None, 'libro', 'genero', ['genero_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Corrección manual (Ejercicio 3): el autogenerate generó
    # `op.drop_constraint(None, ...)` y el downgrade fallaba con
    # "Can't emit DROP CONSTRAINT ... it has no name". Se puso el nombre
    # real de la FK en PostgreSQL (`libro_genero_id_fkey`).
    op.drop_constraint('libro_genero_id_fkey', 'libro', type_='foreignkey')
    op.drop_index(op.f('ix_libro_genero_id'), table_name='libro')
    op.drop_column('libro', 'genero_id')
    op.drop_table('genero')
    # ### end Alembic commands ###
