"""esquema inicial sin genero

Revision ID: 95dd46a75b66
Revises: 
Create Date: 2026-10-09 14:32:12.464767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95dd46a75b66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Correcciones manuales (Ejercicio 3):
    # 1. Se reemplazó `sqlmodel.sql.sqltypes.AutoString()` por `sa.String()`
    #    porque el autogenerate no importó el módulo `sqlmodel` y el
    #    upgrade fallaba con NameError.
    # 2. Se excluyó la tabla `genero` y la columna `libro.genero_id`
    #    (con su índice y su clave foránea): llegan en la segunda
    #    migración del Ejercicio 3.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nacionalidad', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_email'), 'cliente', ['email'], unique=True)
    op.create_table('editorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('libro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('editorial_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('precio > 0', name='ck_libro_precio_positivo'),
    sa.CheckConstraint('stock >= 0', name='ck_libro_stock_no_negativo'),
    sa.ForeignKeyConstraint(['editorial_id'], ['editorial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libro_editorial_id'), 'libro', ['editorial_id'], unique=False)
    op.create_index(op.f('ix_libro_isbn'), 'libro', ['isbn'], unique=True)
    op.create_index(op.f('ix_libro_titulo'), 'libro', ['titulo'], unique=False)
    op.create_table('perfil_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_cliente_cliente_id'), 'perfil_cliente', ['cliente_id'], unique=True)
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('total >= 0', name='ck_venta_total_no_negativo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_cliente_id'), 'venta', ['cliente_id'], unique=False)
    op.create_table('libro_autor',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.CheckConstraint("rol IN ('autor', 'coautor', 'traductor', 'ilustrador')", name='ck_libro_autor_rol_valido'),
    sa.CheckConstraint('orden >= 1', name='ck_libro_autor_orden_minimo'),
    sa.ForeignKeyConstraint(['autor_id'], ['autor.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libro.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'autor_id')
    )
    op.create_index(op.f('ix_libro_autor_autor_id'), 'libro_autor', ['autor_id'], unique=False)
    op.create_table('renglon_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_renglon_cantidad_positiva'),
    sa.CheckConstraint('precio_unitario > 0', name='ck_renglon_precio_unitario_positivo'),
    sa.ForeignKeyConstraint(['libro_id'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renglon_venta_libro_id'), 'renglon_venta', ['libro_id'], unique=False)
    op.create_index(op.f('ix_renglon_venta_venta_id'), 'renglon_venta', ['venta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renglon_venta_venta_id'), table_name='renglon_venta')
    op.drop_index(op.f('ix_renglon_venta_libro_id'), table_name='renglon_venta')
    op.drop_table('renglon_venta')
    op.drop_index(op.f('ix_libro_autor_autor_id'), table_name='libro_autor')
    op.drop_table('libro_autor')
    op.drop_index(op.f('ix_venta_cliente_id'), table_name='venta')
    op.drop_table('venta')
    op.drop_index(op.f('ix_perfil_cliente_cliente_id'), table_name='perfil_cliente')
    op.drop_table('perfil_cliente')
    op.drop_index(op.f('ix_libro_titulo'), table_name='libro')
    op.drop_index(op.f('ix_libro_isbn'), table_name='libro')
    op.drop_index(op.f('ix_libro_editorial_id'), table_name='libro')
    op.drop_table('libro')
    op.drop_table('editorial')
    op.drop_index(op.f('ix_cliente_email'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_table('autor')
    # ### end Alembic commands ###
